apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pizza-hub.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pizza-hub.labels" . | nindent 4 }}
type: Opaque
data:
  db-user: cGl6emE=
  db-password: cGl6emExMjM=
  db-name: cGl6emFodWI=
