{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pizza-hub.redis.name" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pizza-hub.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "pizza-hub.redis.selectorLabels" . | nindent 4 }}
{{- end }}
