apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizza-hub-prod
  namespace: argocd
  labels:
    environment: prod
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/pizza-hub/pizza-hub.git'
    targetRevision: HEAD
    path: infras/apps/pizza-hub/overlays/dev
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pizza-hub-prod  # Separate namespace for prod
    
  syncPolicy:
    # Manual sync for production (safety)
    syncOptions:
    - CreateNamespace=true
