apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: pizza-hub
patches:
  - target:
      kind: Deployment
      name: pizza-app
      version: v1
    path: patches/app-replicas.yaml
  - target:
      kind: Deployment
      name: pizza-app
      version: v1
    path: patches/resources-limit.yaml
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=dev
      - DB_HOST=postgres-svc
      - REDIS_HOST=redis-svc
    name: pizza-config
images:
  - name: pizza-app
    newName: gianglt1/pizza-hub-app
    newTag: 89f01d7c963f8efb2d86d5e9d1feba1b69cbc164
