apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: pizza-hub

# Remove in-cluster databases for production  
  # path: patches/remove-postgres.yaml 
  # path: patches/remove-redis.yaml
patches:
- patch: "- op: remove  \n  path: /spec"
  target:
    kind: Deployment
    name: postgres
    version: v1
- patch: "- op: remove  \n  path: /spec "
  target:
    kind: Deployment
    name: redis
    version: v1
- path: patches/app-replicas.yaml
- path: patches/resources-limits.yaml


configMapGenerator:
- behavior: replace
  literals:
  - ENV=production
  - DB_HOST=pizza-hub-prod.cluster-xxxxx.us-west-2.rds.amazonaws.com
  - DB_PORT=5432
  - DB_SSL_MODE=require
  - REDIS_HOST=pizza-hub-prod.xxxxx.cache.amazonaws.com
  - REDIS_PORT=6379
  - SERVER_PORT=8080
  name: pizza-config


images:
- name: pizza-app
  newName: gianglt1/pizza-hub-app
  newTag: v1.0.0
