apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: pizza-hub

patches:
- path: patches/app-replicas.yaml
- path: patches/resources-limits.yaml

configMapGenerator:
- behavior: merge
  literals:
  - ENV=dev
  - DB_HOST=postgres-svc
  - REDIS_HOST=redis-svc
  name: pizza-config

images:
- name: pizza-app
  newName: gianglt1/pizza-hub-app
  newTag: dev-latest
